credentials_path = "../terraform/traffic-data-pipeline-414619-e2265eb0bbfa.json"
project_id = "traffic-data-pipeline-414619"
region = "us-central1"
bucket_name = "london_traffic_data_bucket"
dataset_id = "london_traffic_data"   
table_id = "london_traffic_table"    